CREATE USER appuser WITH PASSWORD 'app_pass';
CREATE DATABASE sre OWNER appuser;
CREATE USER readonly WITH PASSWORD 'readonly_pass';
\c sre
GRANT CONNECT ON DATABASE sre TO readonly;
GRANT USAGE ON SCHEMA public TO readonly;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO readonly;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO readonly;
